### ISSUE TITLE
阿拉伯数字转中文数字"零"的使用规则可有矛盾？

### ISSUE THREAD

**Issue by lukeaxu** [inte2000/code_for_algo_book#1]
> Page 48 中文数字对“零”的使用总结起来有以下三条规则。
> - 规则 1: 以10000为小节，小节的结尾即使是 0，也不使用“零”。
> - 规则 2: 小节内两个非 0 数字之间要使用“零”。
> - 规则 3: 当小节的“千”位是 0 时，若本小节的 *前一小节* 无其他数字，则不用“零”，否则就要用“零”

考虑数字 `1 0000`，按照规则 1，小节的结尾是 `0000` 所以不使用“零”；按照规则 3，该小节的千位是 `0`，并且前一小节有其他数字 `1`，所以使用“零”，`1 0000` 的中文表示为：**一万**，所以认为规则 1 的优先级大于规则 3

考虑数字 `1 0000 0100`，对于 `0100` 按照规则 3，前面一小节 `0000` 没有除了 `0` 以外的其他数字，所以不用“零”，对于 `0000` 规则 1 和规则 3 都适用，而规则 1 的优先级大于规则 3，所以不用“零”，所以 `1 0000 0100` 根据三条规则表示为：**一亿一百**

> 《[填写票据和结算凭证的基本规定](https://doc.mbalib.com/view/67eb70fff0a0c3fd8b22de893e127fe9.html)》
阿拉伯数字中间有“0”时，中文大写金额要写“零”字。阿拉伯数字中间连续有几个“0”时，中间可以只写一个“零”字

根据上面的规则，`1 0000 0100` 应该表示为：**一亿零一百**

以为可以从规则 1 和 规则 3 合并出一条使用“零”的规则，将三条规则简化为两条规则：
- 规则 1: 小节内两个非 0 数字之间要使用“零”。
- 规则 2: 小节非 `0000` **且**千位为 0 **且**该小节前有其他数字

这样也可以和书中提供的代码直接对应：
```c++
    while(num > 0)
    {
        unsigned int section = num % 10000;
        if(needZero)
        {
            chnStr.insert(0, chnNumChar[0]);
        }
        SectionToChinese(section, strIns);
        /*是否需要节权位？*/
        strIns += (section != 0) ? chnUnitSection[unitPos] : chnUnitSection[0]; 
        chnStr.insert(0, strIns);
        /*千位是0？需要在下一个section补零*/
        needZero = (section < 1000) && (section > 0); 
        num = num / 10000;
        unitPos++;
    }
```

**Comment by inte2000** [comment]
好建议，Good！

















在 2023-06-09 11:32:24，"lukeaxu" ***@***.***> 写道：

Page 48 中文数字对“零”的使用总结起来有以下三条规则。

规则 1: 以10000为小节，小节的结尾即使是 0，也不使用“零”。
规则 2: 小节内两个非 0 数字之间要使用“零”。
规则 3: 当小节的“千”位是 0 时，若本小节的 前一小节 无其他数字，则不用“零”，否则就要用“零”

考虑数字 1 0000，按照规则 1，小节的结尾是 0000 所以不使用“零”；按照规则 3，该小节的千位是 0，并且前一小节有其他数字 1，所以使用“零”，1 0000 的中文表示为：一万，所以认为规则 1 的优先级大于规则 3

考虑数字 1 0000 0100，对于 0100 按照规则 3，前面一小节 0000 没有除了 0 以外的其他数字，所以不用“零”，对于 0000 规则 1 和规则 3 都适用，而规则 1 的优先级大于规则 3，所以不用“零”，所以 1 0000 0100 根据三条规则表示为：一亿一百

《填写票据和结算凭证的基本规定》
阿拉伯数字中间有“0”时，中文大写金额要写“零”字。阿拉伯数字中间连续有几个“0”时，中间可以只写一个“零”字

根据上面的规则，1 0000 0100 应该表示为：一亿零一百

以为可以从规则 1 和 规则 3 合并出一条使用“零”的规则，将三条规则简化为两条规则：

规则 1: 小节内两个非 0 数字之间要使用“零”。
规则 2: 小节非 0000且千位为 0 且该小节前有其他数字

这样也可以和书中提供的代码直接对应：

while(num > 0)
    {
        unsignedint section = num % 10000;
        if(needZero)
        {
            chnStr.insert(0, chnNumChar[0]);
        }
        SectionToChinese(section, strIns);
        /*是否需要节权位？*/
        strIns += (section != 0) ? chnUnitSection[unitPos] : chnUnitSection[0]; 
        chnStr.insert(0, strIns);
        /*千位是0？需要在下一个section补零*/
        needZero = (section < 1000) && (section > 0); 
        num = num / 10000;
        unitPos++;
    }
